{{- if .Values.podDisruptionBudget }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "redis-cluster.fullname" . }}
  labels: {{- include "redis-cluster.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "redis-cluster.matchLabels" . | nindent 6 }}
  {{- toYaml .Values.podDisruptionBudget | nindent 2 }}
{{- end }}
